### ISSUE TITLE
Tapyrus Coreのセットアップ記事を作成する

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-pages#2]

**Comment by oshikawatkm** [comment]
## Berkeley DBのバージョンを整理する
tapyrusdビルド時にインストールするBerkeley DBバージョンを整理する。
- [セットアップドキュメント](https://github.com/chaintope/tapyrus-core/blob/master/doc/build-unix.md#dependency-build-instructions)では`4.8`をインストールする
　- インストール用の[sehllscript](https://github.com/chaintope/tapyrus-core/blob/master/contrib/install_db4.sh)でも4.8を使用
- [Dockerfile(/tapyrus-core/depends/Dockerfile)](https://github.com/chaintope/tapyrus-core/blob/master/depends/Dockerfile)では`5.8`をインストールする前提
どちらが使用されていか調べる。
` --with-incompatible-bdb`オプションを使用するか検討する。
場合によってはdockerで使用するBDBのバージョンを4.8に変更する。

**Comment by oshikawatkm** [comment]
## 環境について
それぞれの環境での構築方法を記事にする
- Ubuntu 20.04
- MacOS
- Docker

**Comment by oshikawatkm** [comment]
## Ubuntu 20.04でインストールに失敗する（調査中）
[セットアップドキュメント](https://github.com/chaintope/tapyrus-core/blob/master/doc/build-unix.md#dependency-build-instructions)にしたがってインストールすると`./configure`実行時に、BDBのヘッダーファイルが見つからないというエラーが発生。

[install_db4.sh](https://github.com/explore)を実行すると以下が発生。
```
....
checking for EVENT... no
configure: error: libevent not found.
```

別途BDBをインストールする[方法](https://baloian.medium.com/how-to-setup-and-run-a-bitcoin-full-node-on-ubuntu-a106fb86dbb3)にしたがって実行するが、同様のエラーが発生。
```
....
checking for EVENT... no
configure: error: libevent not found.
```

`apt list --installed | grep libevent`を実行するとlibeventがインストールできていることは確認できる。
```
libevent-2.1-7/focal,now 2.1.11-stable-1 amd64 [インストール済み、自動]
```

[bitcoind](https://github.com/bitcoin/bitcoin)でインストールすると`./configure`実行時に同様のエラーが発生。
libeventバージョンが関係していると思われる。
```
checking for EVENT... no
configure: error: libevent version 2.1.8 or greater not found.
```
Bitcoindにissue等が建っていないことから、ローカルの環境に問題があると考えられる。

### dependenciesの記述(2022/06/14追記)
以下を見るとlibevent の2.1.8である必要がある？
https://github.com/chaintope/tapyrus-core/blob/master/doc/dependencies.md

`sudo apt-get install libevent-dev=2.1.8`を実行するとversion not foundになる。
```
sudo apt-cache madison  libevent-dev
libevent-dev | 2.1.11-stable-1 | http://jp.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

## 関連部分
https://github.com/chaintope/tapyrus-core/blob/a9f1b9c83758d5da0aed4705f88bfe851a42272d/configure.ac#L1058
https://github.com/chaintope/tapyrus-core/blob/master/depends/packages/libevent.mk

## 結論
自分の環境にのみ問題があり、別のPCでは問題が起きないないため、この問題は無視する。

**Comment by oshikawatkm** [comment]
## Macでのインストールに失敗する（調査中）
[セットアップドキュメント](https://github.com/chaintope/tapyrus-core/blob/master/doc/build-osx.md)通りに進めると`make`コマンド実行時に以下のエラーが発生。
```
  CXX      libtapyrus_common_a-key.o
key.cpp:14:10: fatal error: 'secp256k1.h' file not found
#include <secp256k1.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [libtapyrus_common_a-key.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

## 解決策：libsecp256k1をインストール
`libsecp256k1`ライブラリをインストールする手順の追加が必要
https://github.com/chaintope/secp256k1


## 問題
上記の問題はlibsecp256k1をインストールすることで前進するが、その後、以下のエラーが発生。
```
  AR       leveldb/libmemenv.a
make[3]: *** No rule to make target `libsecp256k1.la'.  Stop.
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

## 解決策
libsecp256k1をサブモジュールとしてインストールする。
```
 git clone --recursive https://github.com/chaintope/tapyrus-core.git
```

git clone 済みの場合
```
git submodule update --init --recursive
```

**Comment by oshikawatkm** [comment]
## [Ubuntu] ドキュメント通りに実行できないコマンド

### tapyrusd権限
```
$ tapyrusd -daemon -datadir=/var/lib/tapyrus-testnet -conf=/etc/tapyrus/tapyrus.conf
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::create_directory: Permission denied: "/var/lib/tapyrus-testnet/prod-1939510133"       
tapyrus in AppInit()  
```
権限エラーが起きるため`sudo`をつけて実行、もしくは`/var/lib/tapyrus-testnet/`の権限を変更しないといけない


### networkidオプション
```
$ tapyrus-cli -networkid=1939510133 -datadir=/var/lib/tapyrus-testnet -conf=/etc/tapyrus/tapyrus.conf getblockchaininfo
Error parsing command line arguments: Invalid parameter -networkid
```
`-networkid`オプションが不要？

## genesisファイル
ドキュメントでは`/var/lib/tapyrus-testnet/genesis.1939510133`になっているが、`$HOME/.tapyrus`を使用する場合`~/.tapyrus/genesis.1939510133`にする

**Comment by azuchi** [comment]
> 権限エラーが起きるため`sudo`をつけて実行、もしくは`/var/lib/tapyrus-testnet/`の権限を変更しないといけない

`-datadir`でパーミッションの無いディレクトリを指定してるからですね。`-conf`と`-datadir`オプションはなくても設定しないように書くのが良いかもしれないですね。Linuxだと`$HOME/.tapyrus`フォルダを作成して、そこにtapyrus.confを作成した上で、`tapyrusd`を起動するような。

> `-networkid`オプションが不要？

tapyrus.confに書いていれば不要ですね。tapyrus.confに記載する記述があれば、ドキュメントから削除して良いかと思います。

**Comment by oshikawatkm** [comment]
# 記事の内容
## Mac
- (準備) ライブラリ・ツールのインストール
  - xcode-select
  - homebrew
  - 依存ライブラリ
- ビルド
- 起動
  - `.tapyrus`ディレクトリを設定する方法での起動
- コマンド実行
  - `getblockchain`のみの確認

## Ubuntu & Debian
- (準備) 依存インストール
  - 依存ライブラリ
ビルド以降はMacと同じ構成

## Docker
- Dockerのインストール
ビルド以降はMacと同じ構成

### 検討事項
- walletの作成も含める？
- テストネットコインの取得までの流れも含める？

**Comment by oshikawatkm** [comment]
## (Ubuntu) バイナリダウンロードによるセットアップ方法追記
記事冒頭にバイナリをダウンロードしてセットアップする方法を記載。
現在執筆済みのものは自分でビルドしたい人向けのビルド手順として紹介。
